name = "backend"
compatibility_date = "2023-12-01"

[vars]
# MY_VARIABLE = "production_value"

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWEwYTA2NzYtN2UzNS00MTkyLTg0NmYtNTliNzRiMzY2NGEyIiwidGVuYW50X2lkIjoiM2Q4NjQxYmMyMTRiNzlhY2Y3ZTExZTZiZjQzZmIzODNhMTQyMjc0OTE0OTM4YzgwNTA2MWIwYmYwMzRjNTY1NCIsImludGVybmFsX3NlY3JldCI6IjIyYjI5NDNiLTYzYzgtNDk2Ny1hZjFmLTAxZmUwYzRmNmMzYiJ9.Uwzt-t-p8LZ3K4V3k01Ob8TbWd4ze3oS_2OCI_8eU80"

JWT_SECRET="mysecretpassword"