name = "backend"
compatibility_date = "2023-12-01"

[vars]
# MY_VARIABLE = "production_value"

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGZjMzc4YzItOWU0Ny00MTg5LTg3NmUtMWZiZDJiZTc5MjdlIiwidGVuYW50X2lkIjoiYTBlMTI2Y2I2MGViYjNmZGE3MmQ5ZmExYjE1MDRlODk2ZjYxNDgwYWM3MmFjMTVhMjg3MTBjNzgwNDZjODA1NyIsImludGVybmFsX3NlY3JldCI6IjFiODBhZjU3LTIxZDItNDc5OS1hNTc4LWVlNDRlMzk0NGQyMyJ9.b-rIVZePhArAv_rQ_WTPOkQk2sBAXILJknd9hvo_-80"

JWT_SECRET="mysecretpassword"